spring:
  application:
    name: loans
  # H2 configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  # Strict input payload validation
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true

# Server port
server:
  port: 8090
